version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/code
    ports:
      - "8000:8989"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
